In [1]:
import pandas as pd

data = {
    "Age": [25, 30, None, 40, 35],
    "Salary": [50000, None, 70000, 90000, 80000],
    "City": ["Delhi", "Mumbai", "Delhi", None, "Pune"],
    "Purchased": ["Yes", "No", "Yes", "No", "Yes"]
}


df = pd.DataFrame(data)

print(df)

    Age   Salary    City Purchased
0  25.0  50000.0   Delhi       Yes
1  30.0      NaN  Mumbai        No
2   NaN  70000.0   Delhi       Yes
3  40.0  90000.0     NaN        No
4  35.0  80000.0    Pune       Yes

In [2]:
df.isnull().sum()

Age          1
Salary       1
City         1
Purchased    0
dtype: int64

In [3]:
df_drop = df.dropna()

print(df_drop)

    Age   Salary   City Purchased
0  25.0  50000.0  Delhi       Yes
4  35.0  80000.0   Pune       Yes

In [4]:
import pandas as pd

data = {
    "Age": [25, 30, None, 40, 35],
    "Salary": [50000, None, 70000, 90000, 80000],
    "City": ["Delhi", "Mumbai", "Delhi", None, "Pune"],
    "Purchased": ["Yes", "No", "Yes", "No", "Yes"]
}


df = pd.DataFrame(data)

print(df)

    Age   Salary    City Purchased
0  25.0  50000.0   Delhi       Yes
1  30.0      NaN  Mumbai        No
2   NaN  70000.0   Delhi       Yes
3  40.0  90000.0     NaN        No
4  35.0  80000.0    Pune       Yes

In [5]:
from sklearn.impute import SimpleImputer


imputer = SimpleImputer(strategy="mean")


df[["Age","Salary"]] = imputer.fit_transform(
    df[["Age","Salary"]]
)


print(df)

    Age   Salary    City Purchased
0  25.0  50000.0   Delhi       Yes
1  30.0  72500.0  Mumbai        No
2  32.5  70000.0   Delhi       Yes
3  40.0  90000.0     NaN        No
4  35.0  80000.0    Pune       Yes

In [6]:
imputer = SimpleImputer(strategy="median")

df[["Salary"]] = imputer.fit_transform(
    df[["Salary"]]
)

In [7]:
imputer = SimpleImputer(strategy="most_frequent")

df[["City"]] = imputer.fit_transform(
    df[["City"]]
)

In [8]:
from sklearn.preprocessing import LabelEncoder


encoder = LabelEncoder()

df["Purchased"] = encoder.fit_transform(
    df["Purchased"]
)

print(df)

    Age   Salary    City  Purchased
0  25.0  50000.0   Delhi          1
1  30.0  72500.0  Mumbai          0
2  32.5  70000.0   Delhi          1
3  40.0  90000.0   Delhi          0
4  35.0  80000.0    Pune          1

In [9]:
df = pd.get_dummies(
    df,
    columns=["City"]
)

print(df)

    Age   Salary  Purchased  City_Delhi  City_Mumbai  City_Pune
0  25.0  50000.0          1        True        False      False
1  30.0  72500.0          0       False         True      False
2  32.5  70000.0          1        True        False      False
3  40.0  90000.0          0        True        False      False
4  35.0  80000.0          1       False        False       True

In [10]:
from sklearn.preprocessing import StandardScaler


scaler = StandardScaler()


df[["Age","Salary"]] = scaler.fit_transform(
    df[["Age","Salary"]]
)


print(df)

   Age    Salary  Purchased  City_Delhi  City_Mumbai  City_Pune
0 -1.5 -1.700840          1        True        False      False
1 -0.5  0.000000          0       False         True      False
2  0.0 -0.188982          1        True        False      False
3  1.5  1.322876          0        True        False      False
4  0.5  0.566947          1       False        False       True

In [11]:
from sklearn.preprocessing import MinMaxScaler


scaler = MinMaxScaler()


df[["Age","Salary"]] = scaler.fit_transform(
    df[["Age","Salary"]]
)

In [12]:
import pandas as pd

from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler


# Load dataset

df = pd.read_csv("data.csv")


# Missing values

imputer = SimpleImputer(strategy="mean")

df[["Age","Salary"]] = imputer.fit_transform(
    df[["Age","Salary"]]
)


# Encoding

df = pd.get_dummies(
    df,
    columns=["City"]
)


# Scaling

scaler = StandardScaler()

df[["Age","Salary"]] = scaler.fit_transform(
    df[["Age","Salary"]]
)


print(df)

FileNotFoundError: [Errno 2] No such file or directory: 'data.csv'

In [13]:
import os

print(os.getcwd())

e:\DSA-ML-30DAYS\ML 30 DAYS\DAY2

In [14]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("mominullptr/fifa-world-cup-2026-dataset")

print("Path to dataset files:", path)

ModuleNotFoundError: No module named 'kagglehub'

In [15]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("mominullptr/fifa-world-cup-2026-dataset")

print("Path to dataset files:", path)

ModuleNotFoundError: No module named 'kagglehub'

In [16]:
import sys

!{sys.executable} -m pip install kagglehub

'e:\DSA-ML-30DAYS\ML' is not recognized as an internal or external command,
operable program or batch file.

In [17]:
import sys

!{sys.executable} -m pip install kagglehub

'e:\DSA-ML-30DAYS\ML' is not recognized as an internal or external command,
operable program or batch file.

In [18]:
"e:\DSA-ML-30DAYS\ML 30 DAYS\.venv\Scripts\activate"

<>:1: SyntaxWarning: invalid escape sequence '\D'
<>:1: SyntaxWarning: invalid escape sequence '\D'
C:\Users\SAKET\AppData\Local\Temp\ipykernel_7932\4203061508.py:1: SyntaxWarning: invalid escape sequence '\D'
  "e:\DSA-ML-30DAYS\ML 30 DAYS\.venv\Scripts\activate"

'e:\\DSA-ML-30DAYS\\ML 30 DAYS\\.venv\\Scripts\x07ctivate'

In [1]:
pip install kagglehub

Collecting kagglehub
  Downloading kagglehub-1.0.2-py3-none-any.whl.metadata (40 kB)
     ---------------------------------------- 0.0/40.1 kB ? eta -:--:--
     ------------------- ------------------ 20.5/40.1 kB 682.7 kB/s eta 0:00:01
     -------------------------------------- 40.1/40.1 kB 635.1 kB/s eta 0:00:00
Collecting kagglesdk<1.0,>=0.1.22 (from kagglehub)
  Downloading kagglesdk-0.1.30-py3-none-any.whl.metadata (13 kB)
Requirement already satisfied: packaging in e:\dsa-ml-30days\ml_30_days\.venv\lib\site-packages (from kagglehub) (26.2)
Collecting pyyaml (from kagglehub)
  Using cached pyyaml-6.0.3-cp312-cp312-win_amd64.whl.metadata (2.4 kB)
Collecting requests (from kagglehub)
  Downloading requests-2.34.2-py3-none-any.whl.metadata (4.8 kB)
Collecting tqdm (from kagglehub)
  Downloading tqdm-4.68.3-py3-none-any.whl.metadata (57 kB)
     ---------------------------------------- 0.0/57.4 kB ? eta -:--:--
     ---------------------------------------- 57.4/57.4 kB 2.9 MB/s eta 0:00:00
Collecting protobuf (from kagglesdk<1.0,>=0.1.22->kagglehub)
  Downloading protobuf-7.35.1-cp310-abi3-win_amd64.whl.metadata (595 bytes)
Collecting charset_normalizer<4,>=2 (from requests->kagglehub)
  Downloading charset_normalizer-3.4.7-cp312-cp312-win_amd64.whl.metadata (41 kB)
     ---------------------------------------- 0.0/41.7 kB ? eta -:--:--
     ---------------------------------------- 41.7/41.7 kB ? eta 0:00:00
Collecting idna<4,>=2.5 (from requests->kagglehub)
  Downloading idna-3.18-py3-none-any.whl.metadata (6.1 kB)
Collecting urllib3<3,>=1.26 (from requests->kagglehub)
  Downloading urllib3-2.7.0-py3-none-any.whl.metadata (6.9 kB)
Collecting certifi>=2023.5.7 (from requests->kagglehub)
  Downloading certifi-2026.6.17-py3-none-any.whl.metadata (2.5 kB)
Requirement already satisfied: colorama in e:\dsa-ml-30days\ml_30_days\.venv\lib\site-packages (from tqdm->kagglehub) (0.4.6)
Downloading kagglehub-1.0.2-py3-none-any.whl (70 kB)
   ---------------------------------------- 0.0/70.6 kB ? eta -:--:--
   ---------------------------------------- 70.6/70.6 kB ? eta 0:00:00
Downloading kagglesdk-0.1.30-py3-none-any.whl (231 kB)
   ---------------------------------------- 0.0/231.0 kB ? eta -:--:--
   ---------------------------- ----------- 163.8/231.0 kB 3.3 MB/s eta 0:00:01
   ---------------------------------------  225.3/231.0 kB 2.8 MB/s eta 0:00:01
   ---------------------------------------- 231.0/231.0 kB 2.8 MB/s eta 0:00:00
Using cached pyyaml-6.0.3-cp312-cp312-win_amd64.whl (154 kB)
Downloading requests-2.34.2-py3-none-any.whl (73 kB)
   ---------------------------------------- 0.0/73.1 kB ? eta -:--:--
   ---------------------------------------- 73.1/73.1 kB 4.2 MB/s eta 0:00:00
Downloading tqdm-4.68.3-py3-none-any.whl (78 kB)
   ---------------------------------------- 0.0/78.3 kB ? eta -:--:--
   ---------------------------------------- 78.3/78.3 kB 4.5 MB/s eta 0:00:00
Downloading certifi-2026.6.17-py3-none-any.whl (133 kB)
   ---------------------------------------- 0.0/133.3 kB ? eta -:--:--
   ---------------------------------------- 133.3/133.3 kB 4.0 MB/s eta 0:00:00
Downloading charset_normalizer-3.4.7-cp312-cp312-win_amd64.whl (159 kB)
   ---------------------------------------- 0.0/159.3 kB ? eta -:--:--
   ----------------------------------- ---- 143.4/159.3 kB 4.3 MB/s eta 0:00:01
   ---------------------------------------- 159.3/159.3 kB 3.2 MB/s eta 0:00:00
Downloading idna-3.18-py3-none-any.whl (65 kB)
   ---------------------------------------- 0.0/65.5 kB ? eta -:--:--
   ---------------------------------------- 65.5/65.5 kB 3.7 MB/s eta 0:00:00
Downloading urllib3-2.7.0-py3-none-any.whl (131 kB)
   ---------------------------------------- 0.0/131.1 kB ? eta -:--:--
   ---------------------------------- ----- 112.6/131.1 kB 3.3 MB/s eta 0:00:01
   ---------------------------------------- 131.1/131.1 kB 2.6 MB/s eta 0:00:00
Downloading protobuf-7.35.1-cp310-abi3-win_amd64.whl (439 kB)
   ---------------------------------------- 0.0/440.0 kB ? eta -:--:--
   ----------- ---------------------------- 122.9/440.0 kB 3.6 MB/s eta 0:00:01
   ------------------------ --------------- 266.2/440.0 kB 4.1 MB/s eta 0:00:01
   ---------------------------------------- 440.0/440.0 kB 3.4 MB/s eta 0:00:00
Installing collected packages: urllib3, tqdm, pyyaml, protobuf, idna, charset_normalizer, certifi, requests, kagglesdk, kagglehub
Successfully installed certifi-2026.6.17 charset_normalizer-3.4.7 idna-3.18 kagglehub-1.0.2 kagglesdk-0.1.30 protobuf-7.35.1 pyyaml-6.0.3 requests-2.34.2 tqdm-4.68.3 urllib3-2.7.0
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.0 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
import kagglehub

path = kagglehub.dataset_download(
    "mominullptr/fifa-world-cup-2026-dataset"
)

print("Dataset path:", path)

e:\DSA-ML-30DAYS\ML_30_DAYS\.venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

Downloading to C:\Users\SAKET\.cache\kagglehub\datasets\mominullptr\fifa-world-cup-2026-dataset\13.archive...

100%|██████████| 49.7k/49.7k [00:00<00:00, 644kB/s]

Extracting files...
Dataset path: C:\Users\SAKET\.cache\kagglehub\datasets\mominullptr\fifa-world-cup-2026-dataset\versions\13

In [3]:
import pandas as pd

from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler


# Load dataset

df = pd.read_csv("data.csv")


# Missing values

imputer = SimpleImputer(strategy="mean")

df[["Age","Salary"]] = imputer.fit_transform(
    df[["Age","Salary"]]
)


# Encoding

df = pd.get_dummies(
    df,
    columns=["City"]
)


# Scaling

scaler = StandardScaler()

df[["Age","Salary"]] = scaler.fit_transform(
    df[["Age","Salary"]]
)


print(df)

FileNotFoundError: [Errno 2] No such file or directory: 'data.csv'

In [4]:
import os

print(os.listdir(path))

['matches.csv', 'matches_detailed.csv', 'match_events.csv', 'referees.csv', 'squads_and_players.csv', 'teams.csv', 'tournament_stages.csv', 'venues.csv']

In [5]:
import pandas as pd
import os

file_path = os.path.join(path, "matches.csv")

df = pd.read_csv(file_path)

df.head()

,match_id,date,kickoff_time_utc,stage_id,venue_id,home_team_id,away_team_id,home_score,away_score,status,home_xg,away_xg,referee_id
0,1,2026-06-11,19:00,1,1,1,2,2.0,0.0,Completed,1.84,0.52,1
1,2,2026-06-11,23:00,1,7,3,4,2.0,1.0,Completed,1.45,1.12,2
2,3,2026-06-12,19:00,1,6,5,6,1.0,1.0,Completed,1.35,0.98,3
3,4,2026-06-12,23:00,1,3,13,14,4.0,1.0,Completed,2.76,0.88,4
4,5,2026-06-13,15:00,1,10,7,8,1.0,1.0,Completed,0.78,1.54,5

In [6]:
df.shape

(72, 13)

In [7]:
df.columns

Index(['match_id', 'date', 'kickoff_time_utc', 'stage_id', 'venue_id',
       'home_team_id', 'away_team_id', 'home_score', 'away_score', 'status',
       'home_xg', 'away_xg', 'referee_id'],
      dtype='str')

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 72 entries, 0 to 71
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   match_id          72 non-null     int64
 1   date              72 non-null     str
 2   kickoff_time_utc  72 non-null     str
 3   stage_id          72 non-null     int64
 4   venue_id          72 non-null     int64
 5   home_team_id      72 non-null     int64
 6   away_team_id      72 non-null     int64
 7   home_score        28 non-null     float64
 8   away_score        28 non-null     float64
 9   status            72 non-null     str
 10  home_xg           28 non-null     float64
 11  away_xg           28 non-null     float64
 12  referee_id        72 non-null     int64
dtypes: float64(4), int64(6), str(3)
memory usage: 7.4 KB

In [9]:
df.isnull().sum()

match_id             0
date                 0
kickoff_time_utc     0
stage_id             0
venue_id             0
home_team_id         0
away_team_id         0
home_score          44
away_score          44
status               0
home_xg             44
away_xg             44
referee_id           0
dtype: int64

In [10]:
pd.set_option('display.max_columns', None)

df.head()

,match_id,date,kickoff_time_utc,stage_id,venue_id,home_team_id,away_team_id,home_score,away_score,status,home_xg,away_xg,referee_id
0,1,2026-06-11,19:00,1,1,1,2,2.0,0.0,Completed,1.84,0.52,1
1,2,2026-06-11,23:00,1,7,3,4,2.0,1.0,Completed,1.45,1.12,2
2,3,2026-06-12,19:00,1,6,5,6,1.0,1.0,Completed,1.35,0.98,3
3,4,2026-06-12,23:00,1,3,13,14,4.0,1.0,Completed,2.76,0.88,4
4,5,2026-06-13,15:00,1,10,7,8,1.0,1.0,Completed,0.78,1.54,5

In [11]:
Pipeline()

NameError: name 'Pipeline' is not defined

In [12]:
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler


pipeline = Pipeline([
    ("imputer", SimpleImputer(strategy="mean")),
    ("scaler", StandardScaler())
])

In [13]:
numerical_pipeline = Pipeline([

    ("imputer",
     SimpleImputer(strategy="mean")),

    ("scaler",
     StandardScaler())

])

In [14]:
categorical_pipeline = Pipeline([

    ("imputer",
     SimpleImputer(strategy="most_frequent")),

    ("encoder",
     OneHotEncoder(handle_unknown="ignore"))

])

NameError: name 'OneHotEncoder' is not defined

In [15]:
from sklearn.preprocessing import OneHotEncoder

In [16]:
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder


categorical_pipeline = Pipeline([

    ("imputer",
     SimpleImputer(strategy="most_frequent")),

    ("encoder",
     OneHotEncoder(handle_unknown="ignore"))

])

In [17]:
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer

from sklearn.impute import SimpleImputer

from sklearn.preprocessing import (
    StandardScaler,
    OneHotEncoder
)

In [18]:
df.head()

,match_id,date,kickoff_time_utc,stage_id,venue_id,home_team_id,away_team_id,home_score,away_score,status,home_xg,away_xg,referee_id
0,1,2026-06-11,19:00,1,1,1,2,2.0,0.0,Completed,1.84,0.52,1
1,2,2026-06-11,23:00,1,7,3,4,2.0,1.0,Completed,1.45,1.12,2
2,3,2026-06-12,19:00,1,6,5,6,1.0,1.0,Completed,1.35,0.98,3
3,4,2026-06-12,23:00,1,3,13,14,4.0,1.0,Completed,2.76,0.88,4
4,5,2026-06-13,15:00,1,10,7,8,1.0,1.0,Completed,0.78,1.54,5

In [19]:
numerical_columns = df.select_dtypes(
    include=["int64", "float64"]
).columns


categorical_columns = df.select_dtypes(
    include=["object"]
).columns


print("Numerical Columns:")
print(numerical_columns)

print("\nCategorical Columns:")
print(categorical_columns)

Numerical Columns:
Index(['match_id', 'stage_id', 'venue_id', 'home_team_id', 'away_team_id',
       'home_score', 'away_score', 'home_xg', 'away_xg', 'referee_id'],
      dtype='str')

Categorical Columns:
Index(['date', 'kickoff_time_utc', 'status'], dtype='str')

C:\Users\SAKET\AppData\Local\Temp\ipykernel_4336\1561490309.py:6: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_columns = df.select_dtypes(

In [20]:
from sklearn.compose import ColumnTransformer


preprocessor = ColumnTransformer([

    ("num",
     numerical_pipeline,
     numerical_columns),

    ("cat",
     categorical_pipeline,
     categorical_columns)

])

In [21]:
X_processed = preprocessor.fit_transform(df)

In [22]:
X_processed.shape

(72, 38)

In [23]:
X_processed = X_processed.toarray()


clean_df = pd.DataFrame(
    X_processed
)


clean_df.head()

AttributeError: 'numpy.ndarray' object has no attribute 'toarray'

In [24]:
from sklearn.compose import ColumnTransformer


preprocessor = ColumnTransformer([

    ("num",
     numerical_pipeline,
     numerical_columns),

    ("cat",
     categorical_pipeline,
     categorical_columns)

])

In [25]:
X_processed = preprocessor.fit_transform(df)

In [26]:
X_processed = X_processed.toarray()


clean_df = pd.DataFrame(
    X_processed
)


clean_df.head()

AttributeError: 'numpy.ndarray' object has no attribute 'toarray'

In [27]:
type(X_processed)

numpy.ndarray

In [28]:
import pandas as pd

clean_df = pd.DataFrame(
    X_processed
)

clean_df.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37
0,-1.708159,0.0,-1.631250,-1.694863,-1.625562,-0.165220,-1.732051,-0.148084,-1.513882,-1.537729,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
1,-1.660042,0.0,-0.370606,-1.550620,-1.481068,-0.165220,0.000000,-0.821867,0.177156,-1.319783,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
2,-1.611925,0.0,-0.580713,-1.406376,-1.336574,-1.090450,0.000000,-0.994632,-0.217419,-1.101837,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
3,-1.563808,0.0,-1.211035,-0.829401,-0.758596,1.685241,0.000000,1.441352,-0.499259,-0.883891,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
4,-1.515691,0.0,0.259716,-1.262132,-1.192079,-1.090450,0.000000,-1.979391,1.360883,-0.665945,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0

In [29]:
feature_names = preprocessor.get_feature_names_out()

clean_df = pd.DataFrame(
    X_processed,
    columns=feature_names
)

clean_df.head()

,num__match_id,num__stage_id,num__venue_id,num__home_team_id,num__away_team_id,num__home_score,num__away_score,num__home_xg,num__away_xg,num__referee_id,cat__date_2026-06-11,cat__date_2026-06-12,cat__date_2026-06-13,cat__date_2026-06-14,cat__date_2026-06-15,cat__date_2026-06-16,cat__date_2026-06-17,cat__date_2026-06-18,cat__date_2026-06-19,cat__date_2026-06-20,cat__date_2026-06-21,cat__date_2026-06-22,cat__date_2026-06-23,cat__date_2026-06-24,cat__date_2026-06-25,cat__date_2026-06-26,cat__date_2026-06-27,cat__date_2026-06-28,cat__date_2026-06-29,cat__kickoff_time_utc_15:00,cat__kickoff_time_utc_18:00,cat__kickoff_time_utc_19:00,cat__kickoff_time_utc_21:00,cat__kickoff_time_utc_22:00,cat__kickoff_time_utc_23:00,cat__kickoff_time_utc_23:59,cat__status_Completed,cat__status_Scheduled
0,-1.708159,0.0,-1.631250,-1.694863,-1.625562,-0.165220,-1.732051,-0.148084,-1.513882,-1.537729,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
1,-1.660042,0.0,-0.370606,-1.550620,-1.481068,-0.165220,0.000000,-0.821867,0.177156,-1.319783,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
2,-1.611925,0.0,-0.580713,-1.406376,-1.336574,-1.090450,0.000000,-0.994632,-0.217419,-1.101837,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
3,-1.563808,0.0,-1.211035,-0.829401,-0.758596,1.685241,0.000000,1.441352,-0.499259,-0.883891,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
4,-1.515691,0.0,0.259716,-1.262132,-1.192079,-1.090450,0.000000,-1.979391,1.360883,-0.665945,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0

In [30]:
clean_df.to_csv(
    "cleaned_fifa_dataset.csv",
    index=False
)